version: '3.8' 

name: ulfia-fatimah

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    configs:
      - source: nginx-conf
        target: /etc/nginx/nginx.conf
    networks:
      - library-network

  mysql:
    image: mysql:latest
    container_name: mysql-server_new
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: library_db
      MYSQL_USER: ulfia_fatimah
      MYSQL_PASSWORD: ulfi123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - library-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_new
    environment:
      PMA_HOST: mysql-server_new
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8081:80"
    networks:
      - library-network

  postgres:
    image: postgres:latest
    container_name: postgres-server_new
    environment:
      POSTGRES_USER: ulfia_fatimah
      POSTGRES_PASSWORD: ulfi_pass
      POSTGRES_DB: library_db_pg
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - library-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-server
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - library-network

  redis:
    image: redis:latest
    container_name: redis-server_new
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - library-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_new
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - library-network

  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: elasticsearch_new
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    networks:
      - library-network

  kibana:
    image: kibana:7.17.10
    container_name: kibana_new
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - library-network

configs:
  nginx-conf:
    file: ./nginx.conf

networks:
  library-network:
    driver: bridge

volumes:
  mysql-data:
  postgres-data:
  redis-data: